# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43230bd68261d2292de3b9d57feacf3beaf2b5b41b462cd3e4b7083a9ca8229f3e0411bc72f8e0561e67224d2aaa48c51056b78dc447cbc5dc174d90b9c5af8f

test:
  secret_key_base: c2988883cec3a9eb3f98a658a82e58ed2a07b9d9ad58977ed2fb29d8c4f6bf172f17091a26deccb86a364ba32677438cc001077b885604eb9bd16167c16a72ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
